version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  node:
    platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: my-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: bookholder
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
