services:
  node:
    image: node:20-alpine
    container_name: bookholder-frontend
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: sh -c 'npm install && npm run dev'
    ports:
      - "3000:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: bookholder-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - bookholder-network

  webserver:
    image: nginx:alpine
    container_name: bookholder-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - bookholder-network

networks:
  bookholder-network:
    driver: bridge
