version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: bookholder-backend
    container_name: bookholder-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: bookholder-webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    image: bookholder-frontend
    container_name: bookholder-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    networks:
      - app-network

  database:
    image: mysql:8.3
    container_name: bookholder-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: bookholder
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
    driver: local
